StudyJP/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

StudyJP/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("index/", views.IndexPage.as_view(), name="index"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("study/", include("quiz.urls", namespace="quiz")),
]

StudyJP/quiz/urls.py
from django.urls import path
from . import views

app_name = "quiz"

urlpatterns = [
    path("", views.IndexVoca.as_view(), name="index"),
    path("all", views.ListVoca.as_view(), name="all"),
    path("quiz/<level>", views.QuizVoca.as_view(), name="quiz"),
]

StudyJP/accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

StudyJP/quiz/models.py
from django.db import models

# Create your models here.
class Voca(models.Model):
    kanji = models.CharField(max_length=256)
    kana = models.CharField(max_length=256)
    pos = models.CharField(max_length=256)  # Parts of speech
    meaning = models.CharField(max_length=256)
    en_example = models.CharField(max_length=256)
    ja_example = models.CharField(max_length=256)
    example_kana = models.CharField(max_length=256)
    level = models.CharField(max_length=32)

StudyJP/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

StudyJP/accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

StudyJP/config/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = "home.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("index"))
        return super().get(request, *args, **kwargs)


class IndexPage(TemplateView):
    template_name = "index.html"


class ThanksPage(TemplateView):
    template_name = "thanks.html"

StudyJP/quiz/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Voca

# Create your views here.


class IndexVoca(generic.TemplateView):
    template_name = "quiz/voca_index.html"


class ListVoca(generic.ListView):
    model = Voca
    template_name = "quiz/voca_list.html"


class QuizVoca(generic.ListView):
    template_name = "quiz/voca_quiz.html"

    paginate_by = 1

    def get_queryset(self):
        return Voca.objects.filter(level=self.kwargs["level"]).order_by("?")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the level
        context["level"] = self.kwargs["level"]
        return context

StudyJP/templates/accounts/login.html
{% extends "base.html" %}

{# at the terminal, run pip install django-bootstrap4 #}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

StudyJP/templates/accounts/signup.html
{% extends "base.html" %}

{# at the terminal, run pip install django-bootstrap4 #}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Sign Up</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

StudyJP/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>StudyJP</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous"/>

    <!-- <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}"> -->

  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">StudyJP</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="btn btn-simple" href="{% url 'quiz:index' %}">Voca</a>
            <a class="btn btn-simple" href="{% url 'accounts:logout' %}">Log out</a>
          {% else %}
            <a class="btn btn-simple" href="{% url 'accounts:login' %}">Log in</a>
            <a class="btn btn-simple" href="{% url 'accounts:signup' %}">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}{% endblock %}
    </div>

    <canvas id="canvas"></canvas>

    <!-- <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script> -->

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function () {
        $('#dataTable').DataTable();
      });
    </script>
    <script>
      $("#vocaQuizAns").hide();
      $("#vocaQuizToggle").on("click", function (e) {
        e.preventDefault();
        $("#vocaQuizAns").toggle('swing');
      });
    </script>
  </body>
</html>

StudyJP/templates/home.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to StudyJP!</h1>

{% endblock %}

StudyJP/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>{{ user.username }} are now logged in!</h1>
  <h2><a href="{% url 'quiz:index' %}">Voca!</a></h2>

</div>

{% endblock %}

StudyJP/templates/quiz/snippets/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

StudyJP/templates/quiz/voca_index.html
{% extends "base.html" %}
{% block content %}
  <h1 class="mt-4">Vocaburaly Section</h1>
  <h2>
    <a href="{% url 'quiz:all' %}">All Voca List!</a>
  </h2>
  <h2>Voca Quiz</h2>
  <ul>
    <li>
      <a href="{% url 'quiz:quiz' level='N3' %}">N3 Voca Quiz</a>
    </li>
    <li>
      <a href="{% url 'quiz:quiz' level='N4' %}">N4 Voca Quiz</a>
    </li>
    <li>
      <a href="{% url 'quiz:quiz' level='N5' %}">N5 Voca Quiz</a>
    </li>
  </ul>

{% endblock %}

StudyJP/templates/quiz/voca_list.html
{% extends "base.html" %}

{% block content %}
<h1 class="mt-4">Vocaburaly <small>(N3~N5)</small></h1>
  <table id="dataTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
        <th>Kanji</th>
        <th>Kana</th>
        <th>pos</th>
        <th>Meaning</th>
        <th>Example(en)</th>
        <th>Example(ja)</th>
        <th>Example Kana</th>
        <th>Level</th>
      </tr>
    </thead>
    <tbody>
      {% for voca in object_list %}
      <tr>
        <td>{{ voca.kanji }}</td>
        <td>{{ voca.kana }}</td>
        <td>{{ voca.pos }}</td>
        <td>{{ voca.meaning }}</td>
        <td>{{ voca.en_example}}</td>
        <td>{{ voca.ja_example}}</td>
        <td>{{ voca.example_kana }}</td>
        <td>{{ voca.level }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


{% endblock %}

StudyJP/templates/quiz/voca_quiz.html
{% extends "base.html" %}

{% block content %}
  <h1 class="mt-4">{{ level }}
    Voca Quizzes</h1>
  <div class="container">
    <div class="list-group">
      {% for voca in object_list %}
        <div class="card mb-3">
          <button class="btn btn-block" id="vocaQuizToggle">
            <h5>
              <ul class="list_inline d-flex">
                <li class="list-inline-item">
                  <small>{{ voca.kana }}</small><br>
                  <h3>{{ voca.kanji }}</h3>
                </li>
                <li class="list-inline-item">
                  <small>{{ voca.pos }}</small>
                </li>
              </ul>
            </h5>
          </button>
          <!-- card-header -->
          <div class="card-body" id="vocaQuizAns">
            <ul>
              <h3>{{ voca.meaning }}</h3>
            </ul>
            <hr>
            {% if voca.en_example %}
            <ul>
              <h5>Example</h5>
              <ul type="none">
                <li>{{ voca.en_example }}</li>
                <li>{{ voca.ja_example }}</li>
              </ul>
            </ul>
            {% else %}
            {% endif %}
          </div>
          <!-- card-body -->
        </div>
        {% include "quiz/snippets/pagination.html" %}
      {% endfor %}
    </div>
  </div>

{% endblock %}

StudyJP/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}